language: java
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://hooks.pubu.im/services/qy81wdpr6zevf2p
    on_success: [always]
    on_failure: [always]
    on_start: [always]