language: java

jdk:
  - oraclejdk8

notifications:
  webhooks: 
    urls:
      - https://hooks.pubu.im/services/qy81wdpr6zevf2p
    on_success: always
    on_failure: always
  
  email:
    recipients:
      - ibmeye@163.com
    on_success: always
    on_failure: always